name: tflite_audio
maintainer: Michael Nguyen
description: Audio classification Tflite package for flutter (iOS & Android). Supports 16KB page sizes for Android 15+. 
version: 0.4.3
homepage: https://github.com/Caldarie/flutter_tflite_audio

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter
  
flutter:
  plugin:
    platforms:
      android:
        package: flutter.tflite_audio
        pluginClass: TfliteAudioPlugin
      ios:
        pluginClass: TfliteAudioPlugin
